/*****+*-*-*---**--*--***---*--*-*--*--**-**--*--***************************
*
*  Homework #: 05
*
*  Academic Integrity Statement:
*
*  I have not used source code obtained from any other unauthorized source, 
*  either modified or unmodified.  Neither have I provided access to my code 
*  to another. The effort I am submitting is my own original work.
*
*  Program Description: This program generates numbers greater than the original number by manipulating the original number by moving the digit in the ones place                         to the highest power of ten, given a seed for the random number , and limits for the range, while also counting the number of times the number is generated.
*
******+*-*-*---**--*--***---*--*-*--*--**-**--*--**************************/

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

// functions declaration
int getInput(int *, int *); 
void getLargerNums(int);
int counterFunction(int);
void getOutput(int,int);

int main(void)
{

  int randomNum; // a variable to store the random number generated by the seed
  int minimumVal; // a variable to store the minimum value entered by the user
  int maximumVal; // a variable to store the maximum value entered by the user
  int count; // a variable to count the number of large numbers generated

  // functions call
  randomNum = getInput(&minimumVal, &maximumVal); 
  count = counterFunction(randomNum);
  getOutput(randomNum, count);

  return 0;
}
/*****+*-*-*--**---*--***---*--*-*--*--**-**--*--***************************
*
*  Function Information
*
*  Name of Function: getInput
*
*  Function Return Type: int
*
*  Parameters (list data type, name, and comment one per line):
*    1.int *min - this function is passed this variable by address and is the minimum value 
*    2.int *max - this function is passed this variable address and is the maximum value
*    3.
*
*  Function Description: This function gets the inputs (seed, min, max) from the user while also displaying an error message if the number entered is not within the range
*
******+*-*-*--**---*--***---*--*-*--*--**-**--*--**************************/
int getInput(int *min, int *max)
{
  int seed; // a temporary variable to store the desired seed value

  do 
  {
    printf("Enter the desired seed value -> ");
    scanf("%d", &seed);
    if(seed < 0)
    {
      printf("\nError! Seed must be a non-negative integer.\n\n");
    }
  } while (seed < 0);

  srand(seed);

  do 
  {
    printf("Enter the desired minimum value -> ");
    scanf("%d", min);

    if(*min < 0) 
    {
      printf("\nError! Minimum must be a non-negative integer.\n\n");
    }
  } while (*min < 0);

  do 
  {
    printf("Enter the desired maximum value -> ");
    scanf("%d", max);

    if(*max <= *min)
    {
      printf("\nError! Maximum value must be greater than %d.\n\n", *min);
    }
  } while (*max <= *min);

  return(rand() % (*max - *min + 1) + *min);
}

/*****+*-*-*---*---*--***---*--*-*--*--**-**--*--***************************
*
*  Function Information
*
*  Name of Function: getLargerNums
*
*  Function Return Type: void
*
*  Parameters (list data type, name, and comment one per line):
*    1. int value - this is the random number generator from the given seed in the previous function
*    2.
*    3.
*
*  Function Description: this number prints out the larger numbers generated from the original number (value) by moving the digit in the ones place to the highest power of ten
*
******+*-*-*---*---*--***---*--*-*--*--**-**--*--**************************/
void getLargerNums(int value) 
{
  int temp; // a variable to temporarily store "value
  int i; // i is the control variable

  for(i = 1; i <= (int) log10(value); i++ ) 
  {
    if(value % ((int) pow(10, i)) > (int) (value / pow(10, ((int) log10(value)) - i + 1)))
    {
      temp = (value % ((int) pow(10, i))) * pow(10, ((int) log10(value)) - (i - 1)) + (value / (int) pow(10, i));
      printf(" %d", temp); 
    }

  }
}
/*****+*-*-**-***-***--**---*--*-*--*--**-**--*--***************************
*
*  Function Information
*
*  Name of Function: counterFunction
*
*  Function Return Type: int
*
*  Parameters (list data type, name, and comment one per line):
*    1.int value - this is the random number generated from the given seed in the previous function
*    2.
*    3.
*
*  Function Description: this function counts the number of times a larger number is generated from the given "value"
*
******+*-*-**-***-***--**---*--*-*--*--**-**--*--**************************/
int counterFunction(int value)
{
  int i; // i is the control variable
  int count; // this variable counts the number of times the condition below is satisfied

  count = 0;
  for(i = 1; i <= (int) log10(value); i++ ) 
  {
    if(value % ((int) pow(10, i)) > (int) (value / pow(10, ((int) log10(value)) - i + 1)))
    {
      count++;
    }
  }
  return count;
}
/*****+*-***--***-***--**---*--*-*--*--**-**--*--***************************
*
*  Function Information
*
*  Name of Function: getOutput
*
*  Function Return Type: void
*
*  Parameters (list data type, name, and comment one per line):
*    1. int value - this is the random number generated from the given seed in the previous function
*    2. int counter - this is the number of times a larger number is generated 
*    3.
*
*  Function Description: this function displays the results in a formatted way and by taking the results of other subfunctions
*
******+*-***--***-***--**---*--*-*--*--**-**--*--**************************/

void getOutput(int value, int count) 
{
  if (count > 0)
  {
    printf("\nLarger numbers generated from %d:", value);
    getLargerNums(value);
    printf("\nCount of larger numbers generated from %d: %d\n", value, count);
  }

  else
  {
    printf("\nCount of larger numbers generated from %d: 0\n", value);
  }
}
